### ISSUE TITLE
amiunique.org is down

### ISSUE THREAD

**Issue by publicarray** [DIVERSIFY-project/amiunique#21]
https://amiunique.org returns 502 Bad Gateway.
![amiunique](https://cloud.githubusercontent.com/assets/5497998/9973985/45eb8834-5ec2-11e5-931b-c9bd4c4b401d.png)

**Comment by plaperdr** [comment]
Thanks for the heads up! We are aware of the problem and we have encountered some technical difficulties on our server. We hope to bring it back online soon (at the latest, it should be back on Monday).

**Comment by plaperdr** [comment]
The website is now back online. I should prepare a page saying that the site is in maintenance in case something like that happens again.

**Comment by publicarray** [comment]
I am glad its back up. That certainly sounds like a good idea.
