### ISSUE TITLE
Microsoft Edge detected as Chrome 42

### ISSUE THREAD

**Issue by Wick** [DIVERSIFY-project/amiunique#23]

**Comment by plaperdr** [comment]
Thanks for bringing this problem to my attention!
The user-agent of Edge is exactly the same as Chrome expect that Microsoft added "Edge" and its version at the end of it:
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240"
I committed a a fix 4c57aa0 and deployed it on the server. It should be working now.
