### ISSUE TITLE
The same phone models (using default browser) born the same fingerprints

### ISSUE THREAD

**Issue by DienNM** [DIVERSIFY-project/amiunique#32]
Hi, I got that issue with 3 new iphones. Do you have any suggest?

**Comment by plaperdr** [comment]
Hello! Thanks for your interest in AmIUnique! 
In my opinion, it is not an issue. If you take 3 totally new iPhones (same model) that just came out from the factory, I would expect them to have the same fingerprint with the default browser. Differences start to appear when users start to make the smartphones their own. For example, if the main language is different or if they switch to a different browser, you will start to notice differences between the phones.
If you have another question or if you want a more detailed explanation, don't hesitate to ask!

**Comment by DienNM** [comment]
Thank you very much for your answer.
Because many people use their phones with default configuration (not add plugin, not change font, use en),.. 
Do you have any idea for identify each of them? :)

**Comment by plaperdr** [comment]
Right now, it is very hard. There may some possibilities because it is rare that users have an exact carbon copy of their configuration but it is pretty much a research topic on its own. Standard fingerprinting scripts don't have the capacity to detect these really subtle differences.

**Comment by DienNM** [comment]
Thank you :)
