### ISSUE TITLE
Do not recommend Ghostery

### ISSUE THREAD

**Issue by devmapper0** [DIVERSIFY-project/amiunique#33]
Please remove Ghostery from recommended tools. It is closed-source and company that owns it have double interests.
[https://en.wikipedia.org/wiki/Ghostery#Criticism](https://en.wikipedia.org/wiki/Ghostery#Criticism)

**Comment by plaperdr** [comment]
Thanks for your interest in AmIUnique!
We are well aware of the criticism around Ghostery but we decided to keep it in our list. Ghostery blocks a really big set of trackers compared to other similar extensions and the share of anonymous data is opt-in by default (and not opt-out). 
If you are interested in the code, it is not a complete black box as it can easily be extracted from the extension packages and it is not obfuscated.
